production:
  type: deploy
  environment: 
    name: production
    url: https://kolecko.sifrovacky.cz
  tags:
    - deploy
    - production
  script:
  - ruby --version
  - bundle install --quiet
  - bundle exec cap production deploy
  only:
  - master

rubocop:
  stage: test
  allow_failure: true
  script:
  - bundle install --quiet
  - bundle exec rubocop

brakeman:
  stage: test
  allow_failure: true
  script:
  - bundle install --quiet
  - bundle exec brakeman --quiet

